# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  host: db
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: <%= ENV["RAILS_DATABASE_NAME"] %>
  username: <%= ENV["RAILS_DATABASE_USERNAME"] %>
  password: <%= ENV["RAILS_DATABASE_PASSWORD"] %>
test:
  <<: *default
  host: db
  database: <%= ENV["RAILS_TEST_DATABASE_NAME"] %>
  username: <%= ENV["RAILS_DATABASE_USERNAME"] %>
  password: <%= ENV["RAILS_DATABASE_PASSWORD"] %>
production:
  <<: *default
  database: task_track_production
  username: task_track
  password: <%= ENV["TASK_TRACK_DATABASE_PASSWORD"] %>
